name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: "20"

      - name: Setup pnpm
        run: |-
          corepack enable
          pnpm --version

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >>$GITHUB_OUTPUT

      - name: Cache pnpm modules
        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm

      - name: Install packages
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Ensure bootstrap is up-to-date
        run: git diff --quiet HEAD -- src/compiler/grammar

      - name: Lint
        run: pnpm xo
